version: '3.8'

services:
  auth:
    image: auth:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    networks:
      - auth-network
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - /app/node_modules
    # restart: always

networks:
  auth-network: